# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aas_python_http_client
from aas_python_http_client.api.aasx_file_server_api_api import AASXFileServerAPIApi  # noqa: E501
from aas_python_http_client.rest import ApiException


class TestAASXFileServerAPIApi(unittest.TestCase):
    """AASXFileServerAPIApi unit test stubs"""

    def setUp(self):
        self.api = AASXFileServerAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_aasxby_package_id(self):
        """Test case for delete_aasxby_package_id

        Deletes a specific AASX package from the server  # noqa: E501
        """
        pass

    def test_get_aasxby_package_id(self):
        """Test case for get_aasxby_package_id

        Returns a specific AASX package from the server  # noqa: E501
        """
        pass

    def test_get_all_aasx_package_ids(self):
        """Test case for get_all_aasx_package_ids

        Returns a list of available AASX packages at the server  # noqa: E501
        """
        pass

    def test_post_aasx_package(self):
        """Test case for post_aasx_package

        Stores the AASX package at the server  # noqa: E501
        """
        pass

    def test_put_aasxby_package_id(self):
        """Test case for put_aasxby_package_id

        Updates the AASX package at the server  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
