# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aas_python_http_client
from aas_python_http_client.api.asset_administration_shell_basic_discovery_api_api import AssetAdministrationShellBasicDiscoveryAPIApi  # noqa: E501
from aas_python_http_client.rest import ApiException


class TestAssetAdministrationShellBasicDiscoveryAPIApi(unittest.TestCase):
    """AssetAdministrationShellBasicDiscoveryAPIApi unit test stubs"""

    def setUp(self):
        self.api = AssetAdministrationShellBasicDiscoveryAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_all_asset_links_by_id(self):
        """Test case for delete_all_asset_links_by_id

        Deletes all specific Asset identifiers linked to an Asset Administration Shell to edit discoverable content  # noqa: E501
        """
        pass

    def test_get_all_asset_administration_shell_ids_by_asset_link(self):
        """Test case for get_all_asset_administration_shell_ids_by_asset_link

        Returns a list of Asset Administration Shell ids linked to specific Asset identifiers  # noqa: E501
        """
        pass

    def test_get_all_asset_links_by_id(self):
        """Test case for get_all_asset_links_by_id

        Returns a list of specific Asset identifiers based on an Asset Administration Shell id to edit discoverable content  # noqa: E501
        """
        pass

    def test_post_all_asset_links_by_id(self):
        """Test case for post_all_asset_links_by_id

        Creates specific Asset identifiers linked to an Asset Administration Shell to edit discoverable content  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
