# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aas_python_http_client
from aas_python_http_client.api.serialization_api_api import SerializationAPIApi  # noqa: E501
from aas_python_http_client.rest import ApiException


class TestSerializationAPIApi(unittest.TestCase):
    """SerializationAPIApi unit test stubs"""

    def setUp(self):
        self.api = SerializationAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_serialization_by_ids(self):
        """Test case for generate_serialization_by_ids

        Returns an appropriate serialization based on the specified format (see SerializationFormat)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
