# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aas_python_http_client
from aas_python_http_client.api.asset_administration_shell_repository_api_api import AssetAdministrationShellRepositoryAPIApi  # noqa: E501
from aas_python_http_client.rest import ApiException


class TestAssetAdministrationShellRepositoryAPIApi(unittest.TestCase):
    """AssetAdministrationShellRepositoryAPIApi unit test stubs"""

    def setUp(self):
        self.api = AssetAdministrationShellRepositoryAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_asset_administration_shell_by_id(self):
        """Test case for delete_asset_administration_shell_by_id

        Deletes an Asset Administration Shell  # noqa: E501
        """
        pass

    def test_delete_file_by_path_aas_repository(self):
        """Test case for delete_file_by_path_aas_repository

        Deletes file content of an existing submodel element at a specified path within submodel elements hierarchy  # noqa: E501
        """
        pass

    def test_delete_submodel_by_id_aas_repository(self):
        """Test case for delete_submodel_by_id_aas_repository

        Deletes the submodel from the Asset Administration Shell and the Repository.  # noqa: E501
        """
        pass

    def test_delete_submodel_element_by_path_aas_repository(self):
        """Test case for delete_submodel_element_by_path_aas_repository

        Deletes a submodel element at a specified path within the submodel elements hierarchy  # noqa: E501
        """
        pass

    def test_delete_submodel_reference_by_id_aas_repository(self):
        """Test case for delete_submodel_reference_by_id_aas_repository

        Deletes the submodel reference from the Asset Administration Shell. Does not delete the submodel itself!  # noqa: E501
        """
        pass

    def test_delete_thumbnail_aas_repository(self):
        """Test case for delete_thumbnail_aas_repository

        """
        pass

    def test_get_all_asset_administration_shells(self):
        """Test case for get_all_asset_administration_shells

        Returns all Asset Administration Shells  # noqa: E501
        """
        pass

    def test_get_all_asset_administration_shells_reference(self):
        """Test case for get_all_asset_administration_shells_reference

        Returns References to all Asset Administration Shells  # noqa: E501
        """
        pass

    def test_get_all_submodel_elements_aas_repository(self):
        """Test case for get_all_submodel_elements_aas_repository

        Returns all submodel elements including their hierarchy  # noqa: E501
        """
        pass

    def test_get_all_submodel_elements_metadata_aas_repository(self):
        """Test case for get_all_submodel_elements_metadata_aas_repository

        Returns all submodel elements including their hierarchy  # noqa: E501
        """
        pass

    def test_get_all_submodel_elements_path_aas_repository(self):
        """Test case for get_all_submodel_elements_path_aas_repository

        Returns all submodel elements including their hierarchy  # noqa: E501
        """
        pass

    def test_get_all_submodel_elements_reference_aas_repository(self):
        """Test case for get_all_submodel_elements_reference_aas_repository

        Returns all submodel elements as a list of References  # noqa: E501
        """
        pass

    def test_get_all_submodel_elements_value_only_aas_repository(self):
        """Test case for get_all_submodel_elements_value_only_aas_repository

        Returns all submodel elements including their hierarchy in the ValueOnly representation  # noqa: E501
        """
        pass

    def test_get_all_submodel_references_aas_repository(self):
        """Test case for get_all_submodel_references_aas_repository

        Returns all submodel references  # noqa: E501
        """
        pass

    def test_get_asset_administration_shell_by_id(self):
        """Test case for get_asset_administration_shell_by_id

        Returns a specific Asset Administration Shell  # noqa: E501
        """
        pass

    def test_get_asset_administration_shell_by_id_reference_aas_repository(self):
        """Test case for get_asset_administration_shell_by_id_reference_aas_repository

        Returns a specific Asset Administration Shell as a Reference  # noqa: E501
        """
        pass

    def test_get_asset_information_aas_repository(self):
        """Test case for get_asset_information_aas_repository

        Returns the Asset Information  # noqa: E501
        """
        pass

    def test_get_file_by_path_aas_repository(self):
        """Test case for get_file_by_path_aas_repository

        Downloads file content from a specific submodel element from the Submodel at a specified path  # noqa: E501
        """
        pass

    def test_get_operation_async_result_aas_repository(self):
        """Test case for get_operation_async_result_aas_repository

        Returns the Operation result of an asynchronous invoked Operation  # noqa: E501
        """
        pass

    def test_get_operation_async_result_value_only_aas_repository(self):
        """Test case for get_operation_async_result_value_only_aas_repository

        Returns the ValueOnly notation of the Operation result of an asynchronous invoked Operation  # noqa: E501
        """
        pass

    def test_get_operation_async_status_aas_repository(self):
        """Test case for get_operation_async_status_aas_repository

        Returns the Operation status of an asynchronous invoked Operation  # noqa: E501
        """
        pass

    def test_get_submodel_by_id_aas_repository(self):
        """Test case for get_submodel_by_id_aas_repository

        Returns the Submodel  # noqa: E501
        """
        pass

    def test_get_submodel_by_id_metadata_aas_repository(self):
        """Test case for get_submodel_by_id_metadata_aas_repository

        Returns the Submodel's metadata elements  # noqa: E501
        """
        pass

    def test_get_submodel_by_id_path_aas_repository(self):
        """Test case for get_submodel_by_id_path_aas_repository

        Returns the Submodel's metadata elements  # noqa: E501
        """
        pass

    def test_get_submodel_by_id_reference_aas_repository(self):
        """Test case for get_submodel_by_id_reference_aas_repository

        Returns the Submodel as a Reference  # noqa: E501
        """
        pass

    def test_get_submodel_by_id_value_only_aas_repository(self):
        """Test case for get_submodel_by_id_value_only_aas_repository

        Returns the Submodel's ValueOnly representation  # noqa: E501
        """
        pass

    def test_get_submodel_element_by_path_aas_repository(self):
        """Test case for get_submodel_element_by_path_aas_repository

        Returns a specific submodel element from the Submodel at a specified path  # noqa: E501
        """
        pass

    def test_get_submodel_element_by_path_metadata_aas_repository(self):
        """Test case for get_submodel_element_by_path_metadata_aas_repository

        Returns the metadata attributes if a specific submodel element from the Submodel at a specified path  # noqa: E501
        """
        pass

    def test_get_submodel_element_by_path_path_aas_repository(self):
        """Test case for get_submodel_element_by_path_path_aas_repository

        Returns a specific submodel element from the Submodel at a specified path in the Path notation  # noqa: E501
        """
        pass

    def test_get_submodel_element_by_path_reference_aas_repository(self):
        """Test case for get_submodel_element_by_path_reference_aas_repository

        Returns the Reference of a specific submodel element from the Submodel at a specified path  # noqa: E501
        """
        pass

    def test_get_submodel_element_by_path_value_only_aas_repository(self):
        """Test case for get_submodel_element_by_path_value_only_aas_repository

        Returns a specific submodel element from the Submodel at a specified path in the ValueOnly representation  # noqa: E501
        """
        pass

    def test_get_thumbnail_aas_repository(self):
        """Test case for get_thumbnail_aas_repository

        """
        pass

    def test_invoke_operation_aas_repository(self):
        """Test case for invoke_operation_aas_repository

        Synchronously invokes an Operation at a specified path  # noqa: E501
        """
        pass

    def test_invoke_operation_async_aas_repository(self):
        """Test case for invoke_operation_async_aas_repository

        Asynchronously invokes an Operation at a specified path  # noqa: E501
        """
        pass

    def test_invoke_operation_async_value_only_aas_repository(self):
        """Test case for invoke_operation_async_value_only_aas_repository

        Asynchronously invokes an Operation at a specified path  # noqa: E501
        """
        pass

    def test_invoke_operation_value_only_aas_repository(self):
        """Test case for invoke_operation_value_only_aas_repository

        Synchronously invokes an Operation at a specified path  # noqa: E501
        """
        pass

    def test_patch_submodel_aas_repository(self):
        """Test case for patch_submodel_aas_repository

        Updates the Submodel  # noqa: E501
        """
        pass

    def test_patch_submodel_by_id_metadata_aas_repository(self):
        """Test case for patch_submodel_by_id_metadata_aas_repository

        Updates the metadata attributes of the Submodel  # noqa: E501
        """
        pass

    def test_patch_submodel_by_id_value_only_aas_repository(self):
        """Test case for patch_submodel_by_id_value_only_aas_repository

        Updates teh values of the Submodel  # noqa: E501
        """
        pass

    def test_patch_submodel_element_value_by_path_aas_repository(self):
        """Test case for patch_submodel_element_value_by_path_aas_repository

        Updates an existing submodel element value at a specified path within submodel elements hierarchy  # noqa: E501
        """
        pass

    def test_patch_submodel_element_value_by_path_metadata(self):
        """Test case for patch_submodel_element_value_by_path_metadata

        Updates the metadata attributes of an existing submodel element value at a specified path within submodel elements hierarchy  # noqa: E501
        """
        pass

    def test_patch_submodel_element_value_by_path_value_only(self):
        """Test case for patch_submodel_element_value_by_path_value_only

        Updates the value of an existing submodel element value at a specified path within submodel elements hierarchy  # noqa: E501
        """
        pass

    def test_post_asset_administration_shell(self):
        """Test case for post_asset_administration_shell

        Creates a new Asset Administration Shell  # noqa: E501
        """
        pass

    def test_post_submodel_element_aas_repository(self):
        """Test case for post_submodel_element_aas_repository

        Creates a new submodel element  # noqa: E501
        """
        pass

    def test_post_submodel_element_by_path_aas_repository(self):
        """Test case for post_submodel_element_by_path_aas_repository

        Creates a new submodel element at a specified path within submodel elements hierarchy  # noqa: E501
        """
        pass

    def test_post_submodel_reference_aas_repository(self):
        """Test case for post_submodel_reference_aas_repository

        Creates a submodel reference at the Asset Administration Shell  # noqa: E501
        """
        pass

    def test_put_asset_administration_shell_by_id(self):
        """Test case for put_asset_administration_shell_by_id

        Updates an existing Asset Administration Shell  # noqa: E501
        """
        pass

    def test_put_asset_information_aas_repository(self):
        """Test case for put_asset_information_aas_repository

        Updates the Asset Information  # noqa: E501
        """
        pass

    def test_put_file_by_path_aas_repository(self):
        """Test case for put_file_by_path_aas_repository

        Uploads file content to an existing submodel element at a specified path within submodel elements hierarchy  # noqa: E501
        """
        pass

    def test_put_submodel_by_id_aas_repository(self):
        """Test case for put_submodel_by_id_aas_repository

        Updates the Submodel  # noqa: E501
        """
        pass

    def test_put_submodel_element_by_path_aas_repository(self):
        """Test case for put_submodel_element_by_path_aas_repository

        Updates an existing submodel element at a specified path within submodel elements hierarchy  # noqa: E501
        """
        pass

    def test_put_thumbnail_aas_repository(self):
        """Test case for put_thumbnail_aas_repository

        """
        pass


if __name__ == '__main__':
    unittest.main()
