# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OperationRequestValueOnly(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'inoutput_arguments': 'ValueOnly',
        'input_arguments': 'ValueOnly',
        'client_timeout_duration': 'str'
    }

    attribute_map = {
        'inoutput_arguments': 'inoutputArguments',
        'input_arguments': 'inputArguments',
        'client_timeout_duration': 'clientTimeoutDuration'
    }

    def __init__(self, inoutput_arguments=None, input_arguments=None, client_timeout_duration=None):  # noqa: E501
        """OperationRequestValueOnly - a model defined in Swagger"""  # noqa: E501
        self._inoutput_arguments = None
        self._input_arguments = None
        self._client_timeout_duration = None
        self.discriminator = None
        if inoutput_arguments is not None:
            self.inoutput_arguments = inoutput_arguments
        if input_arguments is not None:
            self.input_arguments = input_arguments
        self.client_timeout_duration = client_timeout_duration

    @property
    def inoutput_arguments(self):
        """Gets the inoutput_arguments of this OperationRequestValueOnly.  # noqa: E501


        :return: The inoutput_arguments of this OperationRequestValueOnly.  # noqa: E501
        :rtype: ValueOnly
        """
        return self._inoutput_arguments

    @inoutput_arguments.setter
    def inoutput_arguments(self, inoutput_arguments):
        """Sets the inoutput_arguments of this OperationRequestValueOnly.


        :param inoutput_arguments: The inoutput_arguments of this OperationRequestValueOnly.  # noqa: E501
        :type: ValueOnly
        """

        self._inoutput_arguments = inoutput_arguments

    @property
    def input_arguments(self):
        """Gets the input_arguments of this OperationRequestValueOnly.  # noqa: E501


        :return: The input_arguments of this OperationRequestValueOnly.  # noqa: E501
        :rtype: ValueOnly
        """
        return self._input_arguments

    @input_arguments.setter
    def input_arguments(self, input_arguments):
        """Sets the input_arguments of this OperationRequestValueOnly.


        :param input_arguments: The input_arguments of this OperationRequestValueOnly.  # noqa: E501
        :type: ValueOnly
        """

        self._input_arguments = input_arguments

    @property
    def client_timeout_duration(self):
        """Gets the client_timeout_duration of this OperationRequestValueOnly.  # noqa: E501


        :return: The client_timeout_duration of this OperationRequestValueOnly.  # noqa: E501
        :rtype: str
        """
        return self._client_timeout_duration

    @client_timeout_duration.setter
    def client_timeout_duration(self, client_timeout_duration):
        """Sets the client_timeout_duration of this OperationRequestValueOnly.


        :param client_timeout_duration: The client_timeout_duration of this OperationRequestValueOnly.  # noqa: E501
        :type: str
        """
        if client_timeout_duration is None:
            raise ValueError("Invalid value for `client_timeout_duration`, must not be `None`")  # noqa: E501

        self._client_timeout_duration = client_timeout_duration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OperationRequestValueOnly, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OperationRequestValueOnly):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
