# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from aas_python_http_client.models.descriptor import Descriptor  # noqa: F401,E501

class AssetAdministrationShellDescriptor(Descriptor):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'administration': 'AdministrativeInformation',
        'asset_kind': 'AssetKind',
        'asset_type': 'str',
        'endpoints': 'list[Endpoint]',
        'global_asset_id': 'str',
        'id_short': 'str',
        'id': 'str',
        'specific_asset_ids': 'list[SpecificAssetId]',
        'submodel_descriptors': 'list[SubmodelDescriptor]'
    }
    if hasattr(Descriptor, "swagger_types"):
        swagger_types.update(Descriptor.swagger_types)

    attribute_map = {
        'administration': 'administration',
        'asset_kind': 'assetKind',
        'asset_type': 'assetType',
        'endpoints': 'endpoints',
        'global_asset_id': 'globalAssetId',
        'id_short': 'idShort',
        'id': 'id',
        'specific_asset_ids': 'specificAssetIds',
        'submodel_descriptors': 'submodelDescriptors'
    }
    if hasattr(Descriptor, "attribute_map"):
        attribute_map.update(Descriptor.attribute_map)

    def __init__(self, administration=None, asset_kind=None, asset_type=None, endpoints=None, global_asset_id=None, id_short=None, id=None, specific_asset_ids=None, submodel_descriptors=None, *args, **kwargs):  # noqa: E501
        """AssetAdministrationShellDescriptor - a model defined in Swagger"""  # noqa: E501
        self._administration = None
        self._asset_kind = None
        self._asset_type = None
        self._endpoints = None
        self._global_asset_id = None
        self._id_short = None
        self._id = None
        self._specific_asset_ids = None
        self._submodel_descriptors = None
        self.discriminator = None
        if administration is not None:
            self.administration = administration
        if asset_kind is not None:
            self.asset_kind = asset_kind
        if asset_type is not None:
            self.asset_type = asset_type
        if endpoints is not None:
            self.endpoints = endpoints
        if global_asset_id is not None:
            self.global_asset_id = global_asset_id
        if id_short is not None:
            self.id_short = id_short
        self.id = id
        if specific_asset_ids is not None:
            self.specific_asset_ids = specific_asset_ids
        if submodel_descriptors is not None:
            self.submodel_descriptors = submodel_descriptors
        Descriptor.__init__(self, *args, **kwargs)

    @property
    def administration(self):
        """Gets the administration of this AssetAdministrationShellDescriptor.  # noqa: E501


        :return: The administration of this AssetAdministrationShellDescriptor.  # noqa: E501
        :rtype: AdministrativeInformation
        """
        return self._administration

    @administration.setter
    def administration(self, administration):
        """Sets the administration of this AssetAdministrationShellDescriptor.


        :param administration: The administration of this AssetAdministrationShellDescriptor.  # noqa: E501
        :type: AdministrativeInformation
        """

        self._administration = administration

    @property
    def asset_kind(self):
        """Gets the asset_kind of this AssetAdministrationShellDescriptor.  # noqa: E501


        :return: The asset_kind of this AssetAdministrationShellDescriptor.  # noqa: E501
        :rtype: AssetKind
        """
        return self._asset_kind

    @asset_kind.setter
    def asset_kind(self, asset_kind):
        """Sets the asset_kind of this AssetAdministrationShellDescriptor.


        :param asset_kind: The asset_kind of this AssetAdministrationShellDescriptor.  # noqa: E501
        :type: AssetKind
        """

        self._asset_kind = asset_kind

    @property
    def asset_type(self):
        """Gets the asset_type of this AssetAdministrationShellDescriptor.  # noqa: E501


        :return: The asset_type of this AssetAdministrationShellDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._asset_type

    @asset_type.setter
    def asset_type(self, asset_type):
        """Sets the asset_type of this AssetAdministrationShellDescriptor.


        :param asset_type: The asset_type of this AssetAdministrationShellDescriptor.  # noqa: E501
        :type: str
        """

        self._asset_type = asset_type

    @property
    def endpoints(self):
        """Gets the endpoints of this AssetAdministrationShellDescriptor.  # noqa: E501


        :return: The endpoints of this AssetAdministrationShellDescriptor.  # noqa: E501
        :rtype: list[Endpoint]
        """
        return self._endpoints

    @endpoints.setter
    def endpoints(self, endpoints):
        """Sets the endpoints of this AssetAdministrationShellDescriptor.


        :param endpoints: The endpoints of this AssetAdministrationShellDescriptor.  # noqa: E501
        :type: list[Endpoint]
        """

        self._endpoints = endpoints

    @property
    def global_asset_id(self):
        """Gets the global_asset_id of this AssetAdministrationShellDescriptor.  # noqa: E501


        :return: The global_asset_id of this AssetAdministrationShellDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._global_asset_id

    @global_asset_id.setter
    def global_asset_id(self, global_asset_id):
        """Sets the global_asset_id of this AssetAdministrationShellDescriptor.


        :param global_asset_id: The global_asset_id of this AssetAdministrationShellDescriptor.  # noqa: E501
        :type: str
        """

        self._global_asset_id = global_asset_id

    @property
    def id_short(self):
        """Gets the id_short of this AssetAdministrationShellDescriptor.  # noqa: E501


        :return: The id_short of this AssetAdministrationShellDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._id_short

    @id_short.setter
    def id_short(self, id_short):
        """Sets the id_short of this AssetAdministrationShellDescriptor.


        :param id_short: The id_short of this AssetAdministrationShellDescriptor.  # noqa: E501
        :type: str
        """

        self._id_short = id_short

    @property
    def id(self):
        """Gets the id of this AssetAdministrationShellDescriptor.  # noqa: E501


        :return: The id of this AssetAdministrationShellDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AssetAdministrationShellDescriptor.


        :param id: The id of this AssetAdministrationShellDescriptor.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def specific_asset_ids(self):
        """Gets the specific_asset_ids of this AssetAdministrationShellDescriptor.  # noqa: E501


        :return: The specific_asset_ids of this AssetAdministrationShellDescriptor.  # noqa: E501
        :rtype: list[SpecificAssetId]
        """
        return self._specific_asset_ids

    @specific_asset_ids.setter
    def specific_asset_ids(self, specific_asset_ids):
        """Sets the specific_asset_ids of this AssetAdministrationShellDescriptor.


        :param specific_asset_ids: The specific_asset_ids of this AssetAdministrationShellDescriptor.  # noqa: E501
        :type: list[SpecificAssetId]
        """

        self._specific_asset_ids = specific_asset_ids

    @property
    def submodel_descriptors(self):
        """Gets the submodel_descriptors of this AssetAdministrationShellDescriptor.  # noqa: E501


        :return: The submodel_descriptors of this AssetAdministrationShellDescriptor.  # noqa: E501
        :rtype: list[SubmodelDescriptor]
        """
        return self._submodel_descriptors

    @submodel_descriptors.setter
    def submodel_descriptors(self, submodel_descriptors):
        """Sets the submodel_descriptors of this AssetAdministrationShellDescriptor.


        :param submodel_descriptors: The submodel_descriptors of this AssetAdministrationShellDescriptor.  # noqa: E501
        :type: list[SubmodelDescriptor]
        """

        self._submodel_descriptors = submodel_descriptors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssetAdministrationShellDescriptor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetAdministrationShellDescriptor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
