# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from aas_python_http_client.models.has_semantics import HasSemantics  # noqa: F401,E501

class Extension(HasSemantics):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'value_type': 'DataTypeDefXsd',
        'value': 'str',
        'refers_to': 'list[Reference]'
    }
    if hasattr(HasSemantics, "swagger_types"):
        swagger_types.update(HasSemantics.swagger_types)

    attribute_map = {
        'name': 'name',
        'value_type': 'valueType',
        'value': 'value',
        'refers_to': 'refersTo'
    }
    if hasattr(HasSemantics, "attribute_map"):
        attribute_map.update(HasSemantics.attribute_map)

    def __init__(self, name=None, value_type=None, value=None, refers_to=None, *args, **kwargs):  # noqa: E501
        """Extension - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._value_type = None
        self._value = None
        self._refers_to = None
        self.discriminator = None
        self.name = name
        if value_type is not None:
            self.value_type = value_type
        if value is not None:
            self.value = value
        if refers_to is not None:
            self.refers_to = refers_to
        HasSemantics.__init__(self, *args, **kwargs)

    @property
    def name(self):
        """Gets the name of this Extension.  # noqa: E501


        :return: The name of this Extension.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Extension.


        :param name: The name of this Extension.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def value_type(self):
        """Gets the value_type of this Extension.  # noqa: E501


        :return: The value_type of this Extension.  # noqa: E501
        :rtype: DataTypeDefXsd
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type):
        """Sets the value_type of this Extension.


        :param value_type: The value_type of this Extension.  # noqa: E501
        :type: DataTypeDefXsd
        """

        self._value_type = value_type

    @property
    def value(self):
        """Gets the value of this Extension.  # noqa: E501


        :return: The value of this Extension.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Extension.


        :param value: The value of this Extension.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def refers_to(self):
        """Gets the refers_to of this Extension.  # noqa: E501


        :return: The refers_to of this Extension.  # noqa: E501
        :rtype: list[Reference]
        """
        return self._refers_to

    @refers_to.setter
    def refers_to(self, refers_to):
        """Sets the refers_to of this Extension.


        :param refers_to: The refers_to of this Extension.  # noqa: E501
        :type: list[Reference]
        """

        self._refers_to = refers_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Extension, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Extension):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
