# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HasDataSpecification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'embedded_data_specifications': 'list[EmbeddedDataSpecification]'
    }

    attribute_map = {
        'embedded_data_specifications': 'embeddedDataSpecifications'
    }

    def __init__(self, embedded_data_specifications=None):  # noqa: E501
        """HasDataSpecification - a model defined in Swagger"""  # noqa: E501
        self._embedded_data_specifications = None
        self.discriminator = None
        if embedded_data_specifications is not None:
            self.embedded_data_specifications = embedded_data_specifications

    @property
    def embedded_data_specifications(self):
        """Gets the embedded_data_specifications of this HasDataSpecification.  # noqa: E501


        :return: The embedded_data_specifications of this HasDataSpecification.  # noqa: E501
        :rtype: list[EmbeddedDataSpecification]
        """
        return self._embedded_data_specifications

    @embedded_data_specifications.setter
    def embedded_data_specifications(self, embedded_data_specifications):
        """Sets the embedded_data_specifications of this HasDataSpecification.


        :param embedded_data_specifications: The embedded_data_specifications of this HasDataSpecification.  # noqa: E501
        :type: list[EmbeddedDataSpecification]
        """

        self._embedded_data_specifications = embedded_data_specifications

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HasDataSpecification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HasDataSpecification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
