# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from aas_python_http_client.models.referable import Referable  # noqa: F401,E501

class Identifiable(Referable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'administration': 'AdministrativeInformation',
        'id': 'str'
    }
    if hasattr(Referable, "swagger_types"):
        swagger_types.update(Referable.swagger_types)

    attribute_map = {
        'administration': 'administration',
        'id': 'id'
    }
    if hasattr(Referable, "attribute_map"):
        attribute_map.update(Referable.attribute_map)

    def __init__(self, administration=None, id=None, *args, **kwargs):  # noqa: E501
        """Identifiable - a model defined in Swagger"""  # noqa: E501
        self._administration = None
        self._id = None
        self.discriminator = None
        if administration is not None:
            self.administration = administration
        self.id = id
        Referable.__init__(self, *args, **kwargs)

    @property
    def administration(self):
        """Gets the administration of this Identifiable.  # noqa: E501


        :return: The administration of this Identifiable.  # noqa: E501
        :rtype: AdministrativeInformation
        """
        return self._administration

    @administration.setter
    def administration(self, administration):
        """Sets the administration of this Identifiable.


        :param administration: The administration of this Identifiable.  # noqa: E501
        :type: AdministrativeInformation
        """

        self._administration = administration

    @property
    def id(self):
        """Gets the id of this Identifiable.  # noqa: E501


        :return: The id of this Identifiable.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Identifiable.


        :param id: The id of this Identifiable.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Identifiable, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Identifiable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
