# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from aas_python_http_client.models.data_element import DataElement  # noqa: F401,E501

class ModelProperty(DataElement):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'value_type': 'DataTypeDefXsd',
        'value': 'str',
        'value_id': 'Reference',
        'model_type': 'str'
    }
    if hasattr(DataElement, "swagger_types"):
        swagger_types.update(DataElement.swagger_types)

    attribute_map = {
        'value_type': 'valueType',
        'value': 'value',
        'value_id': 'valueId',
        'model_type': 'modelType'
    }
    if hasattr(DataElement, "attribute_map"):
        attribute_map.update(DataElement.attribute_map)

    def __init__(self, value_type=None, value=None, value_id=None, model_type=None, *args, **kwargs):  # noqa: E501
        """ModelProperty - a model defined in Swagger"""  # noqa: E501
        self._value_type = None
        self._value = None
        self._value_id = None
        self._model_type = None
        self.discriminator = None
        self.value_type = value_type
        if value is not None:
            self.value = value
        if value_id is not None:
            self.value_id = value_id
        if model_type is not None:
            self.model_type = model_type
        DataElement.__init__(self, *args, **kwargs)

    @property
    def value_type(self):
        """Gets the value_type of this ModelProperty.  # noqa: E501


        :return: The value_type of this ModelProperty.  # noqa: E501
        :rtype: DataTypeDefXsd
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type):
        """Sets the value_type of this ModelProperty.


        :param value_type: The value_type of this ModelProperty.  # noqa: E501
        :type: DataTypeDefXsd
        """
        if value_type is None:
            raise ValueError("Invalid value for `value_type`, must not be `None`")  # noqa: E501

        self._value_type = value_type

    @property
    def value(self):
        """Gets the value of this ModelProperty.  # noqa: E501


        :return: The value of this ModelProperty.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ModelProperty.


        :param value: The value of this ModelProperty.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def value_id(self):
        """Gets the value_id of this ModelProperty.  # noqa: E501


        :return: The value_id of this ModelProperty.  # noqa: E501
        :rtype: Reference
        """
        return self._value_id

    @value_id.setter
    def value_id(self, value_id):
        """Sets the value_id of this ModelProperty.


        :param value_id: The value_id of this ModelProperty.  # noqa: E501
        :type: Reference
        """

        self._value_id = value_id

    @property
    def model_type(self):
        """Gets the model_type of this ModelProperty.  # noqa: E501


        :return: The model_type of this ModelProperty.  # noqa: E501
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type):
        """Sets the model_type of this ModelProperty.


        :param model_type: The model_type of this ModelProperty.  # noqa: E501
        :type: str
        """

        self._model_type = model_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelProperty, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelProperty):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
