# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from aas_python_http_client.models.has_semantics import HasSemantics  # noqa: F401,E501

class Qualifier(HasSemantics):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'kind': 'QualifierKind',
        'type': 'str',
        'value_type': 'DataTypeDefXsd',
        'value': 'str',
        'value_id': 'Reference'
    }
    if hasattr(HasSemantics, "swagger_types"):
        swagger_types.update(HasSemantics.swagger_types)

    attribute_map = {
        'kind': 'kind',
        'type': 'type',
        'value_type': 'valueType',
        'value': 'value',
        'value_id': 'valueId'
    }
    if hasattr(HasSemantics, "attribute_map"):
        attribute_map.update(HasSemantics.attribute_map)

    def __init__(self, kind=None, type=None, value_type=None, value=None, value_id=None, *args, **kwargs):  # noqa: E501
        """Qualifier - a model defined in Swagger"""  # noqa: E501
        self._kind = None
        self._type = None
        self._value_type = None
        self._value = None
        self._value_id = None
        self.discriminator = None
        if kind is not None:
            self.kind = kind
        self.type = type
        self.value_type = value_type
        if value is not None:
            self.value = value
        if value_id is not None:
            self.value_id = value_id
        HasSemantics.__init__(self, *args, **kwargs)

    @property
    def kind(self):
        """Gets the kind of this Qualifier.  # noqa: E501


        :return: The kind of this Qualifier.  # noqa: E501
        :rtype: QualifierKind
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this Qualifier.


        :param kind: The kind of this Qualifier.  # noqa: E501
        :type: QualifierKind
        """

        self._kind = kind

    @property
    def type(self):
        """Gets the type of this Qualifier.  # noqa: E501


        :return: The type of this Qualifier.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Qualifier.


        :param type: The type of this Qualifier.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def value_type(self):
        """Gets the value_type of this Qualifier.  # noqa: E501


        :return: The value_type of this Qualifier.  # noqa: E501
        :rtype: DataTypeDefXsd
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type):
        """Sets the value_type of this Qualifier.


        :param value_type: The value_type of this Qualifier.  # noqa: E501
        :type: DataTypeDefXsd
        """
        if value_type is None:
            raise ValueError("Invalid value for `value_type`, must not be `None`")  # noqa: E501

        self._value_type = value_type

    @property
    def value(self):
        """Gets the value of this Qualifier.  # noqa: E501


        :return: The value of this Qualifier.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Qualifier.


        :param value: The value of this Qualifier.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def value_id(self):
        """Gets the value_id of this Qualifier.  # noqa: E501


        :return: The value_id of this Qualifier.  # noqa: E501
        :rtype: Reference
        """
        return self._value_id

    @value_id.setter
    def value_id(self, value_id):
        """Sets the value_id of this Qualifier.


        :param value_id: The value_id of this Qualifier.  # noqa: E501
        :type: Reference
        """

        self._value_id = value_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Qualifier, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Qualifier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
