# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnnotatedRelationshipElementValue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'first': 'ReferenceValue',
        'second': 'ReferenceValue',
        'annotations': 'list[ValueOnly]'
    }

    attribute_map = {
        'first': 'first',
        'second': 'second',
        'annotations': 'annotations'
    }

    def __init__(self, first=None, second=None, annotations=None):  # noqa: E501
        """AnnotatedRelationshipElementValue - a model defined in Swagger"""  # noqa: E501
        self._first = None
        self._second = None
        self._annotations = None
        self.discriminator = None
        self.first = first
        self.second = second
        if annotations is not None:
            self.annotations = annotations

    @property
    def first(self):
        """Gets the first of this AnnotatedRelationshipElementValue.  # noqa: E501


        :return: The first of this AnnotatedRelationshipElementValue.  # noqa: E501
        :rtype: ReferenceValue
        """
        return self._first

    @first.setter
    def first(self, first):
        """Sets the first of this AnnotatedRelationshipElementValue.


        :param first: The first of this AnnotatedRelationshipElementValue.  # noqa: E501
        :type: ReferenceValue
        """
        if first is None:
            raise ValueError("Invalid value for `first`, must not be `None`")  # noqa: E501

        self._first = first

    @property
    def second(self):
        """Gets the second of this AnnotatedRelationshipElementValue.  # noqa: E501


        :return: The second of this AnnotatedRelationshipElementValue.  # noqa: E501
        :rtype: ReferenceValue
        """
        return self._second

    @second.setter
    def second(self, second):
        """Sets the second of this AnnotatedRelationshipElementValue.


        :param second: The second of this AnnotatedRelationshipElementValue.  # noqa: E501
        :type: ReferenceValue
        """
        if second is None:
            raise ValueError("Invalid value for `second`, must not be `None`")  # noqa: E501

        self._second = second

    @property
    def annotations(self):
        """Gets the annotations of this AnnotatedRelationshipElementValue.  # noqa: E501


        :return: The annotations of this AnnotatedRelationshipElementValue.  # noqa: E501
        :rtype: list[ValueOnly]
        """
        return self._annotations

    @annotations.setter
    def annotations(self, annotations):
        """Sets the annotations of this AnnotatedRelationshipElementValue.


        :param annotations: The annotations of this AnnotatedRelationshipElementValue.  # noqa: E501
        :type: list[ValueOnly]
        """

        self._annotations = annotations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnnotatedRelationshipElementValue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnnotatedRelationshipElementValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
