# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Environment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset_administration_shells': 'list[AssetAdministrationShell]',
        'submodels': 'list[Submodel]',
        'concept_descriptions': 'list[ConceptDescription]'
    }

    attribute_map = {
        'asset_administration_shells': 'assetAdministrationShells',
        'submodels': 'submodels',
        'concept_descriptions': 'conceptDescriptions'
    }

    def __init__(self, asset_administration_shells=None, submodels=None, concept_descriptions=None):  # noqa: E501
        """Environment - a model defined in Swagger"""  # noqa: E501
        self._asset_administration_shells = None
        self._submodels = None
        self._concept_descriptions = None
        self.discriminator = None
        if asset_administration_shells is not None:
            self.asset_administration_shells = asset_administration_shells
        if submodels is not None:
            self.submodels = submodels
        if concept_descriptions is not None:
            self.concept_descriptions = concept_descriptions

    @property
    def asset_administration_shells(self):
        """Gets the asset_administration_shells of this Environment.  # noqa: E501


        :return: The asset_administration_shells of this Environment.  # noqa: E501
        :rtype: list[AssetAdministrationShell]
        """
        return self._asset_administration_shells

    @asset_administration_shells.setter
    def asset_administration_shells(self, asset_administration_shells):
        """Sets the asset_administration_shells of this Environment.


        :param asset_administration_shells: The asset_administration_shells of this Environment.  # noqa: E501
        :type: list[AssetAdministrationShell]
        """

        self._asset_administration_shells = asset_administration_shells

    @property
    def submodels(self):
        """Gets the submodels of this Environment.  # noqa: E501


        :return: The submodels of this Environment.  # noqa: E501
        :rtype: list[Submodel]
        """
        return self._submodels

    @submodels.setter
    def submodels(self, submodels):
        """Sets the submodels of this Environment.


        :param submodels: The submodels of this Environment.  # noqa: E501
        :type: list[Submodel]
        """

        self._submodels = submodels

    @property
    def concept_descriptions(self):
        """Gets the concept_descriptions of this Environment.  # noqa: E501


        :return: The concept_descriptions of this Environment.  # noqa: E501
        :rtype: list[ConceptDescription]
        """
        return self._concept_descriptions

    @concept_descriptions.setter
    def concept_descriptions(self, concept_descriptions):
        """Sets the concept_descriptions of this Environment.


        :param concept_descriptions: The concept_descriptions of this Environment.  # noqa: E501
        :type: list[ConceptDescription]
        """

        self._concept_descriptions = concept_descriptions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Environment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Environment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
