# coding: utf-8

"""
    DotAAS Part 2 | HTTP/REST | Entire API Collection

    All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"  # noqa: E501

    OpenAPI spec version: V3.0.1
    Contact: info@idtwin.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SubmodelValue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'submodel_elements': 'list[SubmodelElement]'
    }

    attribute_map = {
        'submodel_elements': 'submodelElements'
    }

    def __init__(self, submodel_elements=None):  # noqa: E501
        """SubmodelValue - a model defined in Swagger"""  # noqa: E501
        self._submodel_elements = None
        self.discriminator = None
        if submodel_elements is not None:
            self.submodel_elements = submodel_elements

    @property
    def submodel_elements(self):
        """Gets the submodel_elements of this SubmodelValue.  # noqa: E501


        :return: The submodel_elements of this SubmodelValue.  # noqa: E501
        :rtype: list[SubmodelElement]
        """
        return self._submodel_elements

    @submodel_elements.setter
    def submodel_elements(self, submodel_elements):
        """Sets the submodel_elements of this SubmodelValue.


        :param submodel_elements: The submodel_elements of this SubmodelValue.  # noqa: E501
        :type: list[SubmodelElement]
        """

        self._submodel_elements = submodel_elements

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubmodelValue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubmodelValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
